// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAccrlF239xMc0B9f2eZArEE12WEfzA8WE',
    appId: '1:504791894738:web:ce2cc11e77c0a25c167b0b',
    messagingSenderId: '504791894738',
    projectId: 'traffic-sign-ma',
    authDomain: 'traffic-sign-ma.firebaseapp.com',
    storageBucket: 'traffic-sign-ma.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk-3F_knUpLPRWrx78BwPzmNRDi7Zis0Y',
    appId: '1:504791894738:android:51a0929f0508f58c167b0b',
    messagingSenderId: '504791894738',
    projectId: 'traffic-sign-ma',
    storageBucket: 'traffic-sign-ma.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2ZQH597ZubIjLS_K6wz68HqGgNekj_as',
    appId: '1:504791894738:ios:5232e8f9258614e7167b0b',
    messagingSenderId: '504791894738',
    projectId: 'traffic-sign-ma',
    storageBucket: 'traffic-sign-ma.firebasestorage.app',
    iosBundleId: 'com.example.trafficSignMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2ZQH597ZubIjLS_K6wz68HqGgNekj_as',
    appId: '1:504791894738:ios:5232e8f9258614e7167b0b',
    messagingSenderId: '504791894738',
    projectId: 'traffic-sign-ma',
    storageBucket: 'traffic-sign-ma.firebasestorage.app',
    iosBundleId: 'com.example.trafficSignMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAccrlF239xMc0B9f2eZArEE12WEfzA8WE',
    appId: '1:504791894738:web:7da9804a3d621ea4167b0b',
    messagingSenderId: '504791894738',
    projectId: 'traffic-sign-ma',
    authDomain: 'traffic-sign-ma.firebaseapp.com',
    storageBucket: 'traffic-sign-ma.firebasestorage.app',
  );
}
